# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Pill-Schedule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 5.6.0'
  pod 'R.swift'
  pod 'FirebaseAuth'
  pod 'Firebase'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'FirebaseAnalytics'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Phone'
  pod 'Firebase/Database'
  pod 'FirebaseUI/OAuth'
  pod 'RealmSwift', '~> 10.41'
  # Pods for Pill-Schedule

end
